<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />
  <Import Project="C:/Users/tatal/Documents/My games/Terraria/tModLoader/ModSources/tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>Wolfgodrpg</AssemblyName>
    <LangVersion>latest</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" Exclude="obj\**;bin\**" />
  </ItemGroup>
</Project>